services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY} 
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

volumes:
  meili_data:
