org: aromi
app: aromi-mobile
service: aromi-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**

plugins:
  - serverless-appsync-plugin
  - serverless-dotenv-plugin

resources:
  Resources:
    aromiDBServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AppSyncRDSAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds-data:*
                    - secretsmanager:GetSecretValue
                    - ssm:GetParameter
                  Resource: "*"

appSync:
  name: aromiAppSyncAPI

  authentication:
    type: API_KEY

  apiKeys:
    - name: defaultKey
      description: Default API key for testing
      expiresAfter: 1M

  schema:
    - src/schema/schema.graphql

  dataSources:
    aromiDB:
      type: "RELATIONAL_DATABASE"
      config:
        dbClusterIdentifier: ${env:DB_CLUSTER}
        databaseName: ${env:DB_NAME}
        region: ${env:DB_REGION}
        awsSecretStoreArn: ${ssm:/aromi/rds-secret-arn}
        serviceRoleArn: !GetAtt aromiDBServiceRole.Arn
  
  pipelineFunctions:
    fragrance:
      dataSource: aromiDB
      description: Gets a fragrance
      code: src/resolvers/queries/fragrance.ts

    fragranceAccords:
      dataSource: aromiDB
      description: Gets the accords associated with the fragrance using the fragrance ID
      code: src/resolvers/queries/fragranceAccords.ts

    fragranceNotes:
      dataSource: aromiDB
      description: Gets the notes associated with the fragrance using the fragrance ID
      code: src/resolvers/queries/fragranceNotes.ts

  resolvers:
    Query.fragrances:
      kind: UNIT
      dataSource: aromiDB
      code: src/resolvers/queries/fragrances.ts
    
    Query.fragrance:
      kind: PIPELINE
      dataSource: aromiDB
      code: src/resolvers/queries/fragrancePipeline.ts
      functions:
        - fragrance
        - fragranceAccords
        - fragranceNotes

  logging:
    level: ALL
    retentionInDays: 7

  esbuild:
    target: 'esnext'

useDotenv: true
