org: aromi
app: aromi-mobile
service: aromi-backend

provider:
  name: aws
  region: us-east-2
  environment:
    APPSYNC_ID: ${appsync:id}
    APPSYNC_ARN: ${appsync:arn}
    APPSYNC_URL: ${appsync:url}

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**

plugins:
  - serverless-appsync-plugin
  - serverless-dotenv-plugin
  - serverless-python-requirements

resources:
  Resources:
    aromiDBServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AppSyncRDSAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rds-data:*
                    - secretsmanager:GetSecretValue
                    - ssm:GetParameter
                  Resource: "*"

    cognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UsernameAttributes:
          - "email"
          - "phone_number"
        UserPoolName: aromiUserPool

    cognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: aromiClient
        UserPoolId: !Ref cognitoUserPool

    cognitoUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: "Users belong to this group"
        GroupName: "user"
        Precedence: 1
        RoleArn: !GetAtt cognitoUserIAMRole.Arn
        UserPoolId: !Ref cognitoUserPool

    cognitoUserIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: aromiUserRole
        Description: "IAM role for Users"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated:
                  - "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud": !Ref cognitoUserPool
        Policies:
          - PolicyName: "aromiUserGroupPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "rds-data:*"
                  Resource:
                    - ${env:DB_READ_ARN}

    cognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId: !Ref cognitoUserPoolClient
            ProviderName: !GetAtt cognitoUserPool.ProviderName
        IdentityPoolName: aromiIdentityPool

    cognitoUnauthIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "aromiUnauthRole"
        Description: "IAM role for guest users"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated:
                  - "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud": !Ref cognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": "unauthenticated"
        Policies:
          - PolicyName: "aromiUnauthUserPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "appsync:GraphQL"
                  Resource:
                    - !Sub
                      - "${appsyncApiArn}/types/Query/fields/fragrances"
                      - appsyncApiArn: !GetAtt GraphQlApi.Arn
                    - !Sub
                      - "${appsyncApiArn}/types/Query/fields/fragrance"
                      - appsyncApiArn: !GetAtt GraphQlApi.Arn

    cognitoIdentityPoolRoleAttachment:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId: !Ref cognitoIdentityPool
        Roles:
          unauthenticated: !GetAtt cognitoUnauthIAMRole.Arn

appSync:
  name: aromiAppSyncAPI

  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      userPoolId: ${env:USER_POOL_ID}
  additionalAuthentications:
    - type: AWS_IAM

  schema:
    - src/graphql/schema/schema.graphql

  dataSources:
    aromiDB:
      type: "RELATIONAL_DATABASE"
      config:
        dbClusterIdentifier: ${env:DB_READ_CLUSTER}
        databaseName: ${env:DB_NAME}
        region: ${env:DB_REGION}
        awsSecretStoreArn: ${ssm:/aromi/rds-secret-arn}
        serviceRoleArn: !GetAtt aromiDBServiceRole.Arn

    suggestedFragrancesLambda:
      type: "AWS_LAMBDA"
      config:
        function:
          runtime: python3.11
          functionName: get_suggested_fragrances
          timeout: 30
          handler: src/lambdas/suggestedFragrances/handler.get_suggested_fragrances

  pipelineFunctions:
    fragrances:
      dataSource: aromiDB
      description: Gets fragrances
      code: src/graphql/resolvers/queries/fragrances.ts

    fragrance:
      dataSource: aromiDB
      description: Gets a fragrance
      code: src/graphql/resolvers/queries/fragrance.ts

    fragranceAccords:
      dataSource: aromiDB
      description: Gets the accords associated with the fragrance using the fragrance ID
      code: src/graphql/resolvers/queries/fragranceAccords.ts

    fragranceNotes:
      dataSource: aromiDB
      description: Gets the notes associated with the fragrance using the fragrance ID
      code: src/graphql/resolvers/queries/fragranceNotes.ts
    
    suggestedFragrances:
      dataSource: suggestedFragrancesLambda
      description: Processes fragrance data and scores it
      code: src/graphql/resolvers/queries/suggestedFragrances.ts

  resolvers:
    Query.fragrances:
      kind: UNIT
      dataSource: aromiDB
      code: src/graphql/resolvers/queries/fragrances.ts

    Query.fragrance:
      kind: PIPELINE
      dataSource: aromiDB
      code: src/graphql/resolvers/queries/pipelines/fragrancePipeline.ts
      functions:
        - fragrance
        - fragranceAccords
        - fragranceNotes
    
    Query.suggestedFragrances:
      kind: PIPELINE
      code: src/graphql/resolvers/queries/pipelines/suggestedFragrancesPipeline.ts
      functions:
        - fragrances
        - suggestedFragrances

  logging:
    level: ALL
    retentionInDays: 7

  esbuild:
    target: "esnext"

useDotenv: true
