/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FragranceTrait = "allure" | "balance" | "complexity" | "gender" | "longevity" | "sillage";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ImageFormat = "jpg" | "png";

export type NoteLayer = "base" | "fill" | "middle" | "top";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accord {
  color: Generated<string>;
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  id: Generated<number>;
  name: string;
  updatedAt: Timestamp | null;
}

export interface CollectionFragrance {
  collectionId: number;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  fragranceId: number;
  id: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
}

export interface FragranceAccord {
  accordId: number;
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  fragranceId: number;
  id: Generated<number>;
  updatedAt: Timestamp | null;
  votes: Generated<number>;
}

export interface FragranceAccordVote {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  fragranceAccordId: number;
  id: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface FragranceCollection {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number | null;
}

export interface FragranceImage {
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  format: ImageFormat;
  fragranceId: number;
  id: Generated<number>;
  s3Key: string;
  updatedAt: Timestamp | null;
}

export interface FragranceNote {
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  fragranceId: number;
  id: Generated<number>;
  layer: Generated<NoteLayer>;
  noteId: number;
  updatedAt: Timestamp | null;
  votes: Generated<number>;
}

export interface FragranceNoteVote {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  fragranceNoteId: number;
  id: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface FragranceReview {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  fragranceId: number | null;
  id: Generated<number>;
  rating: number;
  reviewText: string | null;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
  votes: Generated<number>;
}

export interface FragranceReviewVote {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  fragranceReviewId: number;
  id: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
  vote: number;
}

export interface Fragrance {
  brand: string;
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  dislikesCount: number;
  id: Generated<number>;
  likesCount: number;
  name: string;
  rating: number | null;
  reviewsCount: number;
  updatedAt: Timestamp | null;
}

export interface FragranceTrait {
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  fragranceId: number;
  id: Generated<number>;
  trait: FragranceTrait;
  updatedAt: Timestamp | null;
  value: Generated<Numeric | null>;
}

export interface FragranceTraitVote {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  fragranceTraitId: number;
  id: Generated<number>;
  updatedAt: Generated<Timestamp>;
  userId: number;
  value: Numeric;
}

export interface FragranceVote {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  fragranceId: number;
  id: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
  vote: number;
}

export interface Note {
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  id: Generated<number>;
  name: string;
  s3Key: Generated<string | null>;
  updatedAt: Timestamp | null;
}

export interface User {
  cognitoId: string | null;
  createdAt: Timestamp | null;
  deletedAt: Timestamp | null;
  email: Generated<string>;
  id: Generated<number>;
  updatedAt: Timestamp | null;
  username: string | null;
}

export interface DB {
  accords: Accord;
  collectionFragrances: CollectionFragrance;
  fragranceAccords: FragranceAccord;
  fragranceAccordVotes: FragranceAccordVote;
  fragranceCollections: FragranceCollection;
  fragranceImages: FragranceImage;
  fragranceNotes: FragranceNote;
  fragranceNoteVotes: FragranceNoteVote;
  fragranceReviews: FragranceReview;
  fragranceReviewVotes: FragranceReviewVote;
  fragrances: Fragrance;
  fragranceTraits: FragranceTrait;
  fragranceTraitVotes: FragranceTraitVote;
  fragranceVotes: FragranceVote;
  notes: Note;
  users: User;
}
